### Listar todas as tarefas
GET http://localhost:5000/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js",
    "descricao": "Estudar Node.js para desenvolver aplicações web",
    "categoriaId": "6d091456-5a2f-4b5a-98fc-f1a3b50a627d"
}

### Alterar Tarefa 8146c84f-0dbf-4ed8-9ae8-84f559944078
PATCH http://localhost:5000/api/tarefas/alterar/8146c84f-0dbf-4ed8-9ae8-84f559944078
Content-Type: application/json

{
    "titulo": "Estudar Node.js",
    "descricao": "Estudar Node.js para desenvolver aplicações web",
    "categoriaId": "6d091456-5a2f-4b5a-98fc-f1a3b50a627d",
    "status": "Concluída"
}

### Lista Concluidas
GET http://localhost:5000/api/tarefas/concluidas

### Lista Não Concluidas
GET http://localhost:5000/api/tarefas/naoconcluidas
